name: reviewdog
on: [pull_request]
jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: tflint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: "true"
          tflint_rulesets: "azurerm google"
          flags: --recursive
